export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY"//SAGA
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED"//REDUCER
export const GET_MAINCATEGORY = "GET_MAINCATEGORY"//SAGA
export const GET_MAINCATEGORY_RED = "GET_MAINCATEGORY_RED"//REDUCER
export const UPDATE_MAINCATEGORY = "UPDATE_MAINCATEGORY"//SAGA
export const UPDATE_MAINCATEGORY_RED = "UPDATE_MAINCATEGORY_RED"//REDUCER
export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY"//SAGA
export const DELETE_MAINCATEGORY_RED = "DELETE_MAINCATEGORY_RED"//REDUCER

